AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - Gemfile.lock
    - Rakefile
  TargetRubyVersion: 2.4

Style/DotPosition:
  EnforcedStyle: trailing

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "default": "()"
    "%i": "[]"
    "%w": "[]"

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/routes.rb"
    - "**/**/*.rake"

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true


Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Style/EmptyLinesAroundBlockBody:
  Description: "Keeps track of empty lines around block bodies."
  Enabled: false

Style/EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: true

Style/EndOfLine:
  Description: 'Use Unix-style line endings.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#crlf'
  Enabled: true

# Indent one level for follow-up lines
# https://github.com/troessner/reek/issues/553
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-w'
  Enabled: false
